# Bridge Geometry Script
# Generated by Bridge Geometry Studio

import ospgrillage as og
from math import *

# Unit definitions
kilo = 1e3
milli = 1e-3
N = 1
m = 1
mm = milli * m
m2 = m ** 2
m3 = m ** 3
m4 = m ** 4
kN = kilo * N
MPa = N / ((mm) ** 2)
GPa = kilo * MPa


# Material definition
material = og.create_material(material="concrete",
code="AS5100-2017", grade="32MPa")


# Section definitions
edge_longitudinal_section = og.create_section(
    A=0.93 * m2,
    J=0.19 * m3,
    Iz=0.35 * m4,
    Iy=0.21 * m4,
    Az=0.44 * m2,
    Ay=0.26 * m2
)

longitudinal_section = og.create_section(
    A=1.02 * m2,
    J=0.19 * m3,
    Iz=0.37 * m4,
    Iy=0.36 * m4,
    Az=0.5 * m2,
    Ay=0.31 * m2
)

transverse_section = og.create_section(
    A=0.5 * m2,
    J=0.01 * m3,
    Iy=0.33 * m4,
    Iz=0.0 * m4,
    Ay=0.42 * m2,
    Az=0.42 * m2,
    unit_width=True
)


end_transverse_section = og.create_section(
    A=0.25 * m2,
    J=0.0 * m3,
    Iy=0.04 * m4,
    Iz=0.0 * m4,
    Ay=0.21 * m2,
    Az=0.21 * m2
)

longitudinal_beam = og.create_member(section=longitudinal_section, material=material)

edge_longitudinal_beam = og.create_member(
    section=edge_longitudinal_section, material=material
)
transverse_slab = og.create_member(section=transverse_section, material=material)

end_transverse_slab = og.create_member(
    section=end_transverse_section, material=material
)



# Create grillage model
model = og.create_grillage(
    bridge_name="My Bridge",
    long_dim=30.0 * m,
    width=10.0 * m,
    skew=[0.0,0.0],
    num_long_grid=5,  # Number of grid lines
    num_trans_grid=10,
    ext_to_int_dist = 2.5 * m,
    edge_beam_dist=0.5 * m,
    mesh_type="Ortho"  # ('Ortho' or 'Oblique')
)


# Member assignments
model.set_member(longitudinal_beam, member="interior_main_beam")
model.set_member(longitudinal_beam, member="exterior_main_beam_1")
model.set_member(longitudinal_beam, member="exterior_main_beam_2")
model.set_member(edge_longitudinal_beam, member="edge_beam")
model.set_member(transverse_slab, member="transverse_slab")
model.set_member(end_transverse_slab, member="start_edge")
model.set_member(end_transverse_slab, member="end_edge")

model.create_osp_model(pyfile=False)
og.opsv.plot_model(az_el=(-90, 0),element_labels=0, node_labels=0)
fig = og.plt.gcf()
fig.set_size_inches(8, 8)
og.plt.show()

